modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]]
modId="tabby"
version="${file.jarVersion}"
displayName="Tabby Reforged"
#logoFile="logo.png"
authors="AzureDoomC, Fruitloopins"
description='''
Alter the maximum amount of players and rows that can be displayed on the player list
'''
[[dependencies.tabby]]
    modId="forge"
    mandatory=true
    versionRange="[43.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tabby]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
